# We assume this file is in <OMNIORB_TOP>/src/services/omniNotify/mkattlib/mkBOAlib
# Ergo, ../../../../.. gets you to <OMNIORB_TOP>, and from there,
# src/services/omniNotify/mkattlib/mkBOAlib gets you back to the current directory.

TOP=../../../../..
CURRENT=src/services/omniNotify/mkattlib/mkBOAlib

include $(TOP)/config/config.mk
