# We assume this file is in <OMNIORB_TOP>/src/services/omniNotify/lib.
# Ergo, ../../../.. gets you to <OMNIORB_TOP>, and from there,
# src/services/omniNotify/lib gets you back to the current directory.

TOP=../../../..
CURRENT=src/services/omniNotify/lib

include $(TOP)/config/config.mk

