// -*- Mode: C++; -*-

//                              File      : RDIParser_y.h
//                              Package   : omniNotify-Library
//                              Created on: 1-Jan-1998
//                              Authors   : gruber&panagos
//
//    Copyright (C) 1998-2003 AT&T Laboratories -- Research
//
//    This file is part of the omniNotify library
//    and is distributed with the omniNotify release.
//
//    The omniNotify library is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Library General Public
//    License as published by the Free Software Foundation; either
//    version 2 of the License, or (at your option) any later version.
//
//    This library is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//    Library General Public License for more details.
//
//    You should have received a copy of the GNU Library General Public
//    License along with this library; if not, write to the Free
//    Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
//    02111-1307, USA
//
// -------------------------------------------------------------------
// ** This file automatically generated by running buildgens.sh in    
//    <top>/src/services/omniNotify/lib  Rebuild at your own risk!    
// -------------------------------------------------------------------

#ifndef _RDI_PARSER_Y_H_
#define _RDI_PARSER_Y_H_

typedef union{
  /* the type of yylval */
  void* noval;     /* should be set to NULL */
  char* sb;
  RDI_Constraint* cexpr;
} YYSTYPE;
#define	TOK_DIGITS	257
#define	TOK_EXPONENT	258
#define	TOK_IDENT	259
#define	TOK_STRING	260
#define	TOK_EQ	261
#define	TOK_NE	262
#define	TOK_LE	263
#define	TOK_LT	264
#define	TOK_GE	265
#define	TOK_GT	266
#define	TOK_AND	267
#define	TOK_OR	268
#define	TOK_DEFAULT	269
#define	TOK_EXIST	270
#define	TOK_NOT	271
#define	TOK_IN	272
#define	TOK_SUBSTR	273
#define	TOK_DOT	274
#define	TOK_PLUS	275
#define	TOK_MINUS	276
#define	TOK_MUL	277
#define	TOK_DIV	278
#define	TOK_PCNT	279
#define	TOK_LPAR	280
#define	TOK_RPAR	281
#define	TOK_LB	282
#define	TOK_RB	283
#define	TOK_DOLLAR	284
#define	TOK_TRUE	285
#define	TOK_FALSE	286
#define	TOK_OTHER	287
#define	UMINUS	288
#define	UPLUS	289


#endif

